
choices =[('fundamentals of defence studies', 'Fundamentals of Defence Studies'),
('introduction to war studies', 'Introduction to War Studies'),
('introduction to history', 'Introduction to History'),
('introduction to political science', 'Introduction to Political Science'),
('elements of defence administration', 'Elements of Defence Administration'),
('introduction to peace studies', 'Introduction to Peace Studies'),
('introduction to military psychology', 'Introduction to Military Psychology'),
('french/arabic for beginners I', 'French/Arabic for Beginners I'),
('use of english I', 'Use of English I'),
('introduction to security studies', 'Introduction to Security Studies'),
('introduction to international relations', 'Introduction to International Relations'),
('introduction to comparative politics', 'Introduction to Comparative Politics'),
('introduction to peace studies and conflict resolution', 'Introduction to Peace Studies and Conflict Resolution'),
('elements of military leadership', 'Elements of Military Leadership'),
('introduction to regional integration', 'Introduction to Regional Integration'),
('french for beginners II', 'French for Beginners II'),
('use of library, study skills and ICT', 'Use of Library, Study Skills and ICT'),
('theories of security studies', 'Theories of Security Studies'),
('theories of peace and conflict studies', 'Theories of Peace and Conflict Studies'),
('theoris of war', 'Theories of War'),
('nigerian national security', 'Nigerian National Security'),
('defence economics', 'Defence Economics'),
('science, technology and defence', 'Science, Technology and Defence'),
('defence administration', 'Defence Administration'),
('environment and sustainable development', 'Environment and Sustainable Development'),
('sociology of nigerian people and culture I', 'Sociology of Nigerian People and Culture I'),
('history and philosophy of science', 'History and Philosophy of Science'),
('theories of military leadership', 'Theories of Military Leadership'),
('ict and defence', 'ICT and Defence'),
('human security', 'Human Security'),
('nigerian defence foreign policy', 'Nigerian Defence Foreign Policy'),
('nigerian government and politics', 'Nigerian Government and Politics'),
('military mapping', 'Military Mapping'),
('french/arabic for beginners', 'French/Arabic for Beginners'),
('peace studies and conflict resolution', 'Peace Studies and Conflict Resolution'),
('research methodology', 'Research Methodology'),
('confilit, security and development', 'Conflict, Security and Development'),
('military operations and tactics', 'Military Operations and Tactics'),
('terrorism and political violence', 'Terrorism and Political Violence'),
('military aid to civil authority', 'Military Aid to Civil Authority'),
('law of armed conflict', 'Law of Armed Conflict'),
('entrepreneurship studies', 'Entrepreneurship Studies'),
('general psychology', 'General Psychology'),
('economic and management sciences I', 'Economic and Management Sciences I'),
('history of political thought II', 'History of Political Thought II'),
('history and philosopy of science', 'History and Philosophy of Science'),
('campaign planning and operational estimates', 'Campaign Planning and Operational Estimates'),
('ethics of military operations', 'Ethics of Military Operations'),
('military operations other than war', 'Military Operations Other Than War'),
('military alliances and security regiment', 'Military Alliances and Security Regiment'),
('perspectives in military doctrine', 'Perspectives in Military Doctrine'),
('international law and diplomacy', 'International Law and Diplomacy'),
('defence diplomacy', 'Defence Diplomacy'),
('french for beginners VI', 'French for Beginners VI'),
('military psychology', 'Military Psychology'),
('economic and management sciences II', 'Economic and Management Sciences II'),
('use of english', 'Use of English'),
('comparative derence policy', 'Comparative Defence Policy'),
('civil military relations', 'Civil-Military Relations'),
('arms control and disarmament', 'Arms Control and Disarmament'),
('joint and combined military operations', 'Joint and Combined Military Operations'),
('counter-terrorism and counter-insurgency operations', 'Counter-Terrorism and Counter-Insurgency Operations'),
('inter-agency collaboration', 'Inter-Agency Collaboration'),
('defence transformation', 'Defence Transformation'),
('military industrial complex', 'Military Industrial Complex'),
('strategic communication', 'Strategic Communication'),
('military logistics and supply chain', 'Military Logistics and Supply Chain'),
('security sector reforms', 'Security Sector Reforms'),
('defence order of battle', 'Defence Order of Battle'),
('international peacekeeping', 'International Peacekeeping'),
('military intelligence', 'Military Intelligence'),
('cybersecurity', 'Cybersecurity'),
('final year project', 'Final Year Project'),
('introduction to elements of physical geography I', 'Introduction to Elements of Physical Geography I'),
('introduction to elements of human geography I', 'Introduction to Elements of Human Geography I'),
('elementary surveying', 'Elementary Surveying'),
('introduction to practical geography', 'Introduction to Practical Geography'),
('map analysis', 'Map Analysis'),
('principles of economics I', 'Principles of Economics I'),
('introduction to maths for economics/social sciences I', 'Introduction to Maths for Economics/Social Sciences I'),
('introduction to elements of physical geography II', 'Introduction to Elements of Physical Geography II'),
('introduction to elements of human geography II', 'Introduction to Elements of Human Geography II'),
('local field studies', 'Local Field Studies'),
('introduction to environmental sciences', 'Introduction to Environmental Sciences'),
('principles of economics II', 'Principles of Economics II'),
('introduction to maths or economics/social sciences II', 'Introduction to Maths or Economics/Social Sciences II'),
('spatial organization of society', 'Spatial Organization of Society'),
('introductory geomorphology', 'Introductory Geomorphology'),
('elementary statistics for geographers I', 'Elementary Statistics for Geographers I'),
('introductory cartography', 'Introductory Cartography'),
('introduction to geographic information system', 'Introduction to Geographic Information System'),
('geographic thought theory I', 'Geographic Thought Theory I'),
('air photo interpretation', 'Air Photo Interpretation'),
('structure of nigerian economy I', 'Structure of Nigerian Economy I'),
('introductory geomorphology and soil geography II', 'Introductory Geomorphology and Soil Geography II'),
('elementary statistics for geographers II', 'Elementary Statistics for Geographers II'),
('introduction to biogeography and climatology', 'Introduction to Biogeography and Climatology'),
('local field studies', 'Local Field Studies'),
('geography thought theory', 'Geography Thought Theory'),
('leadership and critical thinking skills', 'Leadership and Critical Thinking Skills'),
('africa in world politics', 'Africa in World Politics'),
('structure of the nigerian economy II', 'Structure of the Nigerian Economy II'),
('research methods', 'Research Methods'),
('advanced quantitative techniques I', 'Advanced Quantitative Techniques I'),
('geomorphology', 'Geomorphology'),
('economic geography', 'Economic Geography'),
('population geography', 'Population Geography'),
('biogeography', 'Biogeography'),
('advance map interpretation and analysis', 'Advance Map Interpretation and Analysis'),
('settlement geography', 'Settlement Geography'),
('transport geography', 'Transport Geography'),
('soil geography', 'Soil Geography'),
('vegetation studies', 'Vegetation Studies'),
('field course', 'Field Course'),
('advanced quantitative techniques II', 'Advanced Quantitative Techniques II'),
('regional geography of africa', 'Regional Geography of Africa'),
('advanced cartography', 'Advanced Cartography'),
('population geography II', 'Population Geography II'),
('photogrammetry', 'Photogrammetry'),
('hydrology', 'Hydrology'),
('ecosystems', 'Ecosystems'),
('land evaluation', 'Land Evaluation'),
('oceanography', 'Oceanography'),
('systematic geography of nigeria', 'Systematic Geography of Nigeria'),
('contemporary philosophy and methodology in geography I', 'Contemporary Philosophy and Methodology in Geography I'),
('geographic information system', 'Geographic Information System'),
('military geography', 'Military Geography'),
('remote sensing', 'Remote Sensing'),
('applied climatology', 'Applied Climatology'),
('the developed world', 'The Developed World'),
('arid land', 'Arid Land'),
('political geography', 'Political Geography'),
('medical geography', 'Medical Geography'),
('humid regions', 'Humid Regions'),
('logistical geography', 'Logistical Geography'),
('navigational techniques', 'Navigational Techniques'),
('contemporary philosophy and methodology in geography II', 'Contemporary Philosophy and Methodology in Geography II'),
('military terrain evaluation', 'Military Terrain Evaluation'),
('regional development and planning', 'Regional Development and Planning'),
('the developed world', 'The Developed World'),
('original research project', 'Original Research Project'),
('introduction to history', 'Introduction to History'),
('introduction to economic history', 'Introduction to Economic History'),
('nigeria before 1800 AD', 'Nigeria Before 1800 AD'),
('history of africa from 1500 - 1800 AD', 'History of Africa from 1500 - 1800 AD'),
('islamic revolutions in west africa', 'Islamic Revolutions in West Africa'),
('europe to the age of revolution', 'Europe to the Age of Revolution'),
('war and society in africa to 1900', 'War and Society in Africa to 1900'),
('history of west africa 1500 - 1800 AD', 'History of West Africa 1500 - 1800 AD'),
('north africa from first conquest of egypt to 1500', 'North Africa from First Conquest of Egypt to 1500'),
('archaelogy of the nok, benin and oyo areas', 'Archaeology of the Nok, Benin and Oyo Areas'),
('evolution of the theory and art of war', 'Evolution of the Theory and Art of War'),
('blacks in diaspora', 'Blacks in Diaspora'),
('nigeria 1800-1900', 'Nigeria 1800-1900'),
('economic history of nigeria in the 19th century', 'Economic History of Nigeria in the 19th Century'),
('africa and european imperialism', 'Africa and European Imperialism'),
('history of southern africa from circa 1400-present', 'History of Southern Africa from circa 1400-Present'),
('history of the nigerian army', 'History of the Nigerian Army'),
('europe from french revolution to the 2nd world war', 'Europe from French Revolution to the 2nd World War'),
('introduction to comparative politics I', 'Introduction to Comparative Politics I'),
('history of latin america and caribbean since 1500 AD', 'History of Latin America and Caribbean Since 1500 AD'),
('history of east and central africa since 1800 AD', 'History of East and Central Africa Since 1800 AD'),
('history of the USA since 1877', 'History of the USA Since 1877'),
('history of the nigerian armed forces', 'History of the Nigerian Armed Forces'),
('history of russia 19th century', 'History of Russia 19th Century'),
('economic history of west africa in the 19th and 20th centuries', 'Economic History of West Africa in the 19th and 20th Centuries'),
('introduction to comparative politics II', 'Introduction to Comparative Politics II'),
('nigeria, 1900-1970', 'Nigeria, 1900-1970'),
('research methodology I', 'Research Methodology I'),
('africa and the outside world since 1900', 'Africa and the Outside World Since 1900'),
('history of the commonwealth', 'History of the Commonwealth'),
('war and peace in the 20th century', 'War and Peace in the 20th Century'),
('problems and issues in africa historiography', 'Problems and Issues in Africa Historiography'),
('economic history of USA in the 19th century', 'Economic History of USA in the 19th Century'),
('ussr from 1950-1950', 'USSR from 1950-1950'),
('nigeria during the inter-war periods', 'Nigeria During the Inter-War Periods'),
('comparative industrial growth of usa, ussr, japan and china', 'Comparative Industrial Growth of USA, USSR, Japan and China'),
('problems and prospects of regional economic development in west africa', 'Problems and Prospects of Regional Economic Development in West Africa'),
('air power since 1914', 'Air Power Since 1914'),
('the nigerian civil war', 'The Nigerian Civil War'),
('the military in colonial africa', 'The Military in Colonial Africa'),
('emerging issues in military history', 'Emerging Issues in Military History'),
('research method II', 'Research Method II'),
('nigeria 1970-present', 'Nigeria 1970-Present'),
('theory and art of war from 1945-present', 'Theory and Art of War from 1945-Present'),
('comparative parliamentary studies (nigeria, britain, france and india)', 'Comparative Parliamentary Studies (Nigeria, Britain, France, and India)'),
('war and society in the middle east', 'War and Society in the Middle East'),
('naval warfare since trafalgar', 'Naval Warfare Since Trafalgar'),
('the military in independent africa', 'The Military in Independent Africa'),
('land and labour in africa 1850-1950', 'Land and Labour in Africa 1850-1950'),
('colonial wars in nigeria I', 'Colonial Wars in Nigeria I'),
('terrorism in world history', 'Terrorism in World History'),
('economic history of nigeria in the 20th and 21st centuries', 'Economic History of Nigeria in the 20th and 21st Centuries'),
('oau/au-a study of african international relations', 'OAU/AU - A Study of African International Relations'),
('international peacekeeping', 'International Peacekeeping'),
('philosophy of history', 'Philosophy of History'),
('colonial wars in nigeria II', 'Colonial Wars in Nigeria II'),
('modern african political thoughts', 'Modern African Political Thoughts'),
('supervised project', 'Supervised Project'),
('french phonetics', 'French Phonetics'),
('french corrective grammar', 'French Corrective Grammar'),
('reading/listening comprehension', 'Reading/Listening Comprehension'),
('introduction to french composition', 'Introduction to French Composition'),
('practical french I', 'Practical French I'),
('introduction to a 2nd foreign language', 'Introduction to a 2nd Foreign Language'),
('french phonetics', 'French Phonetics'),
('french grammar', 'French Grammar'),
('reading/listening comprehension', 'Reading/Listening Comprehension'),
('advance french composition', 'Advance French Composition'),
('practical french', 'Practical French'),
('introduction to a 2nd foreign language', 'Introduction to a 2nd Foreign Language'),
('introduction to psychology', 'Introduction to Psychology'),
('translation theory and practice', 'Translation Theory and Practice'),
('french grammatical structures I', 'French Grammatical Structures I'),
('french phonetics and phonology I', 'French Phonetics and Phonology I'),
('advanced practical french I', 'Advanced Practical French I'),
('introduction to french literary genre: prose', 'Introduction to French Literary Genre: Prose'),
('second foreign lang', 'Second Foreign Language'),
('introduction to international relations', 'Introduction to International Relations'),
('translation: "version" and "theme"', 'Translation: "Version" and "Theme"'),
('french grammatical structures', 'French Grammatical Structures'),
('french phonetics and phonology II', 'French Phonetics and Phonology II'),
('advanced practical french II', 'Advanced Practical French II'),
('french drama and poetry', 'French Drama and Poetry'),
('survey of french literature 16th and 17th centuries', 'Survey of French Literature 16th and 17th Centuries'),
('introduction to political analysis', 'Introduction to Political Analysis'),
('translation I', 'Translation I'),
('advance studies in french language structure', 'Advance Studies in French Language Structure'),
('french phonetics and phonology', 'French Phonetics and Phonology'),
('french culture and civilisation', 'French Culture and Civilisation'),
('comparative african literature written in english and french', 'Comparative African Literature Written in English and French'),
('introduction to french military terminologies', 'Introduction to French Military Terminologies'),
('french literature of 19th century', 'French Literature of 19th Century'),
('research methodology I', 'Research Methodology I'),
('translation II', 'Translation II'),
('advance studies in french language structure II', 'Advance Studies in French Language Structure II'),
('creative writing in french', 'Creative Writing in French'),
('caribbean french literature', 'Caribbean French Literature'),
('introduction to african literature written in french', 'Introduction to African Literature Written in French'),
('the sociolinguistics of french', 'The Sociolinguistics of French'),
('advance french military terminologies', 'Advance French Military Terminologies'),
('french literature of the 19th century', 'French Literature of the 19th Century'),
('introduction to project writing/research methodology', 'Introduction to Project Writing/Research Methodology'),
('advance translation I', 'Advance Translation I'),
('linguistics applied to the teaching of french language', 'Linguistics Applied to the Teaching of French Language'),
('caribbean francophone literature', 'Caribbean Francophone Literature'),
('french literature of the 20th century: drama, prose and poetry', 'French Literature of the 20th Century: Drama, Prose, and Poetry'),
('advanced creative writing in french', 'Advanced Creative Writing in French'),
('post-independence francophone-african literature', 'Post-Independence Francophone-African Literature'),
('advance translation II', 'Advance Translation II'),
('linguistics applied to the teaching of french language', 'Linguistics Applied to the Teaching of French Language'),
('caribbean francophone literature', 'Caribbean Francophone Literature'),
('french literature of the 20th century', 'French Literature of the 20th Century'),
('literary criticism in french', 'Literary Criticism in French'),
('post-independence francophone-african literature', 'Post-Independence Francophone-African Literature'),
('final year essay', 'Final Year Essay'),
('grammar', 'Grammar'),
('introduction to arabic literature', 'Introduction to Arabic Literature'),
('reading skills', 'Reading Skills'),
('writing skills', 'Writing Skills'),
('rhetoric', 'Rhetoric'),
('introduction to a second foreign language', 'Introduction to a Second Foreign Language'),
('introduction to arabic novel', 'Introduction to Arabic Novel'),
('translation', 'Translation'),
('text from ancient arabic literature', 'Text from Ancient Arabic Literature'),
('defence and security terms', 'Defence and Security Terms'),
('computer studies in arabic', 'Computer Studies in Arabic'),
('introduction to essay writing', 'Introduction to Essay Writing'),
('introduction to a second foreign language', 'Introduction to a Second Foreign Language'),
('computer application/ICT', 'Computer Application/ICT'),
('grammar', 'Grammar'),
('arabic literature', 'Arabic Literature'),
('reading skills', 'Reading Skills'),
('morphology', 'Morphology'),
('introduction to nigerian arabic literature', 'Introduction to Nigerian Arabic Literature'),
('computer study in arabic', 'Computer Study in Arabic'),
('second foreign language III', 'Second Foreign Language III'),
('grammar III', 'Grammar III'),
('rhetoric II', 'Rhetoric II'),
('translation II', 'Translation II'),
('writing of nigerian arabic scholars', 'Writing of Nigerian Arabic Scholars'),
('computer study in arabic', 'Computer Study in Arabic'),
('second foreign language IV', 'Second Foreign Language IV'),
('grammar IV', 'Grammar IV'),
('rhetoric IV', 'Rhetoric IV'),
('translation IV', 'Translation IV'),
('socio-linguistics of arabic', 'Socio-Linguistics of Arabic'),
('arabic literature in the modern world', 'Arabic Literature in the Modern World'),
('islamic literature in nigeria', 'Islamic Literature in Nigeria'),
('project', 'Project'),
('introduction to political science', 'Introduction to Political Science'),
('introduction to public administration', 'Introduction to Public Administration'),
('introduction to political ideologies', 'Introduction to Political Ideologies'),
('nigerian government and politics', 'Nigerian Government and Politics'),
('introduction to political analysis', 'Introduction to Political Analysis'),
('theories of international relations', 'Theories of International Relations'),
('introduction to public policy analysis', 'Introduction to Public Policy Analysis'),
('political sociology', 'Political Sociology'),
('development administration', 'Development Administration'),
('comparative government', 'Comparative Government'),
('public finance', 'Public Finance'),
('political parties and pressure groups', 'Political Parties and Pressure Groups'),
('nigerian political thought', 'Nigerian Political Thought'),
('local government in nigeria', 'Local Government in Nigeria'),
('public administration and society', 'Public Administration and Society'),
('comparative foreign policy', 'Comparative Foreign Policy'),
('public personnel administration', 'Public Personnel Administration'),
('international law and organization', 'International Law and Organization'),
('public policy implementation', 'Public Policy Implementation'),
('political culture', 'Political Culture'),
('african political thought', 'African Political Thought'),
('public enterprise management', 'Public Enterprise Management'),
('public policy and development', 'Public Policy and Development'),
('government and politics of the middle east', 'Government and Politics of the Middle East'),
('urban government', 'Urban Government'),
('political economy of development', 'Political Economy of Development'),
('gender and politics', 'Gender and Politics'),
('government and politics of east africa', 'Government and Politics of East Africa'),
('introduction to international politics', 'Introduction to International Politics'),
('political parties', 'Political Parties'),
('development planning and administration', 'Development Planning and Administration'),
('political violence and conflict resolution', 'Political Violence and Conflict Resolution'),
('public policy evaluation', 'Public Policy Evaluation'),
('political communication', 'Political Communication'),
('government and politics of west africa', 'Government and Politics of West Africa'),
('introduction to comparative government', 'Introduction to Comparative Government'),
('introduction to international law', 'Introduction to International Law'),
('strategic studies', 'Strategic Studies'),
('economic policies and development', 'Economic Policies and Development'),
('political theories', 'Political Theories'),
('public budgeting and financial management', 'Public Budgeting and Financial Management'),
('international political economy', 'International Political Economy'),
('government and politics of nigeria', 'Government and Politics of Nigeria'),
('international relations in africa', 'International Relations in Africa'),
('administrative theories', 'Administrative Theories'),
('administrative law', 'Administrative Law'),
('foreign policy analysis', 'Foreign Policy Analysis'),
('political leadership and communication', 'Political Leadership and Communication'),
('development theories and strategies', 'Development Theories and Strategies'),
('research methods in political science', 'Research Methods in Political Science'),
('democratic theory and practice', 'Democratic Theory and Practice'),
('comparative public administration', 'Comparative Public Administration'),
('political parties and pressure groups', 'Political Parties and Pressure Groups'),
('theories of comparative politics', 'Theories of Comparative Politics'),
('international organizations', 'International Organizations'),
('local government administration', 'Local Government Administration'),
('public administration and public policy', 'Public Administration and Public Policy'),
('administrative processes and behaviour', 'Administrative Processes and Behaviour'),
('global governance', 'Global Governance'),
('regional integration', 'Regional Integration'),
('foreign policy making in nigeria', 'Foreign Policy Making in Nigeria'),
('government and politics of africa', 'Government and Politics of Africa'),
('public administration theory', 'Public Administration Theory'),
('public policy analysis and evaluation', 'Public Policy Analysis and Evaluation'),
('conflict analysis and resolution', 'Conflict Analysis and Resolution'),
('public personnel management', 'Public Personnel Management'),
('politics of development', 'Politics of Development'),
('international law and diplomacy', 'International Law and Diplomacy'),
('public enterprise management', 'Public Enterprise Management'),
('development administration', 'Development Administration'),
('research methodology in political science', 'Research Methodology in Political Science'),
('global environmental politics', 'Global Environmental Politics'),
('security studies', 'Security Studies'),
('foreign policy analysis', 'Foreign Policy Analysis'),
('globalization and politics', 'Globalization and Politics'),
('political sociology', 'Political Sociology'),
('politics of human rights', 'Politics of Human Rights'),
('democratic governance', 'Democratic Governance'),
('terrorism and counter-terrorism', 'Terrorism and Counter-Terrorism'),
('governance and development', 'Governance and Development'),
('political economy of development', 'Political Economy of Development'),
('gender and politics', 'Gender and Politics'),
('international political economy', 'International Political Economy'),
('public administration and democratic governance', 'Public Administration and Democratic Governance'),
('public policy analysis', 'Public Policy Analysis'),
('comparative public administration', 'Comparative Public Administration'),
('security in africa', 'Security in Africa'),
('foreign policy analysis', 'Foreign Policy Analysis'),
('public sector management', 'Public Sector Management'),
('human rights and democratization', 'Human Rights and Democratization'),
('international institutions', 'International Institutions'),
('policy studies', 'Policy Studies'),
('security management', 'Security Management'),
('development administration', 'Development Administration'),
('research methods in political science', 'Research Methods in Political Science'),
('public administration and public policy', 'Public Administration and Public Policy'),
('conflict resolution and peace studies', 'Conflict Resolution and Peace Studies'),
('political psychology', 'Political Psychology'),
('democracy and governance', 'Democracy and Governance'),
('international organizations', 'International Organizations'),
('foreign policy analysis', 'Foreign Policy Analysis'),
('public policy process', 'Public Policy Process'),
('security and intelligence studies', 'Security and Intelligence Studies'),
('international relations theory', 'International Relations Theory'),
('public policy and administration', 'Public Policy and Administration'),
('international organizations', 'International Organizations'),
('security and conflict studies', 'Security and Conflict Studies'),
('foreign policy analysis', 'Foreign Policy Analysis'),
('governance and development', 'Governance and Development'),
('research methods in political science', 'Research Methods in Political Science'),
('public administration and public policy', 'Public Administration and Public Policy'),
('conflict resolution and peace studies', 'Conflict Resolution and Peace Studies'),
('political psychology', 'Political Psychology'),
('democracy and governance', 'Democracy and Governance'),
('international organizations', 'International Organizations'),
('foreign policy analysis', 'Foreign Policy Analysis'),
('public policy process', 'Public Policy Process'),
('security and intelligence studies', 'Security and Intelligence Studies'),
('international relations theory', 'International Relations Theory'),
('public policy and administration', 'Public Policy and Administration'),
('international organizations', 'International Organizations'),
('security and conflict studies', 'Security and Conflict Studies'),
('comparative politics', 'Comparative Politics'),
('international political economy', 'International Political Economy'),
('international relations', 'International Relations'),
('security studies', 'Security Studies'),
('human rights', 'Human Rights'),
('public administration', 'Public Administration'),
('diplomatic studies', 'Diplomatic Studies'),
('international organization', 'International Organization'),
('conflict resolution', 'Conflict Resolution'),
('foreign policy analysis', 'Foreign Policy Analysis'),
('research methodology', 'Research Methodology'),
('african politics', 'African Politics'),
('global governance', 'Global Governance'),
('development studies', 'Development Studies'),
('government and politics of nigeria', 'Government and Politics of Nigeria'),
('public policy and administration', 'Public Policy and Administration'),
('gender and politics', 'Gender and Politics'),
('comparative politics', 'Comparative Politics'),
('international political economy', 'International Political Economy'),
('international relations', 'International Relations'),
('security studies', 'Security Studies'),
('human rights', 'Human Rights'),
('public administration', 'Public Administration'),
('diplomatic studies', 'Diplomatic Studies'),
('international organization', 'International Organization'),
('conflict resolution', 'Conflict Resolution'),
('foreign policy analysis', 'Foreign Policy Analysis'),
('research methodology', 'Research Methodology'),
('african politics', 'African Politics'),
('global governance', 'Global Governance'),
('development studies', 'Development Studies'),
('government and politics of nigeria', 'Government and Politics of Nigeria'),
('public policy and administration', 'Public Policy and Administration'),
('gender and politics', 'Gender and Politics'),
('supervised research project I', 'Supervised Research Project I'),
('comparative politics', 'Comparative Politics'),
('supervised research project II', 'Supervised Research Project II'),
('politics of human rights', 'Politics of Human Rights'),
('political thought', 'Political Thought'),
('conflict and security in africa', 'Conflict and Security in Africa'),
('economics of public administration', 'Economics of Public Administration'),
('public policy process', 'Public Policy Process'),
('public sector reform in nigeria', 'Public Sector Reform in Nigeria'),
('e-governance', 'E-Governance'),
('project management', 'Project Management'),
('intergovernmental relations', 'Intergovernmental Relations'),
('leadership and administration', 'Leadership and Administration'),
('globalization and public administration', 'Globalization and Public Administration'),
('management of public enterprises', 'Management of Public Enterprises'),
('policy analysis', 'Policy Analysis'),
('development and public policy', 'Development and Public Policy'),
('fiscal policy and administration', 'Fiscal Policy and Administration'),
('conflict management and resolution', 'Conflict Management and Resolution'),
('ethics in governance', 'Ethics in Governance'),
('local government administration', 'Local Government Administration'),
('nigeria in world affairs', 'Nigeria in World Affairs'),
('comparative political systems', 'Comparative Political Systems'),
('international economic relations', 'International Economic Relations'),
('politics and administration of foreign aid', 'Politics and Administration of Foreign Aid'),
('public policy implementation and evaluation', 'Public Policy Implementation and Evaluation'),
('federalism and intergovernmental relations', 'Federalism and Intergovernmental Relations'),
('leadership in africa', 'Leadership in Africa'),
('economic analysis for public administration', 'Economic Analysis for Public Administration'),
('political development in africa', 'Political Development in Africa'),
('economics of development', 'Economics of Development'),
('public finance', 'Public Finance'),
('public policy evaluation', 'Public Policy Evaluation'),
('development policy analysis', 'Development Policy Analysis'),
('research methodology', 'Research Methodology'),
('policy planning and analysis', 'Policy Planning and Analysis'),
('financial management in the public sector', 'Financial Management in the Public Sector'),
('administration of public enterprises', 'Administration of Public Enterprises'),
('public sector reform in africa', 'Public Sector Reform in Africa'),
('development administration', 'Development Administration'),
('african political economy', 'African Political Economy'),
('conflict and development', 'Conflict and Development'),
('gender and development', 'Gender and Development'),
('international relations', 'International Relations'),
('development communication', 'Development Communication'),
('politics and administration of international aid', 'Politics and Administration of International Aid'),
('social policy and development', 'Social Policy and Development'),
('project management in public administration', 'Project Management in Public Administration'),
('regional economic integration', 'Regional Economic Integration'),
('human rights in public administration', 'Human Rights in Public Administration'),
('administrative theory', 'Administrative Theory'),
('project', 'Project'),
('introduction to the use of english I', 'Introduction to the Use of English I'),
('introduction to the use of english II', 'Introduction to the Use of English II'),
('fundamentals of grammar', 'Fundamentals of Grammar'),
('phonetics and phonology of english', 'Phonetics and Phonology of English'),
('history and structure of the english language I', 'History and Structure of the English Language I'),
('reading skills I', 'Reading Skills I'),
('introduction to phonetics and phonology', 'Introduction to Phonetics and Phonology'),
('creative writing', 'Creative Writing'),
('history and structure of the english language II', 'History and Structure of the English Language II'),
('reading skills II', 'Reading Skills II'),
('introduction to syntax and semantics', 'Introduction to Syntax and Semantics'),
('advanced reading skills', 'Advanced Reading Skills'),
('introduction to morphology', 'Introduction to Morphology'),
('history of the english language I', 'History of the English Language I'),
('use of english', 'Use of English'),
('socio-linguistics of english', 'Socio-Linguistics of English'),
('introduction to syntax and semantics', 'Introduction to Syntax and Semantics'),
('creative writing', 'Creative Writing'),
('english lexicology', 'English Lexicology'),
('history of the english language II', 'History of the English Language II'),
('use of english', 'Use of English'),
('linguistics', 'Linguistics'),
('stylistics', 'Stylistics'),
('sociolinguistics', 'Sociolinguistics'),
('phonology', 'Phonology'),
('morphology', 'Morphology'),
('semantics and pragmatics', 'Semantics and Pragmatics'),
('syntax', 'Syntax'),
('language acquisition', 'Language Acquisition'),
('variation in english language', 'Variation in English Language'),
('advanced english grammar', 'Advanced English Grammar'),
('english phonetics and phonology', 'English Phonetics and Phonology'),
('english morphology', 'English Morphology'),
('english syntax', 'English Syntax'),
('english semantics', 'English Semantics'),
('english pragmatics', 'English Pragmatics'),
('socio-linguistics', 'Socio-Linguistics'),
('english dialects', 'English Dialects'),
('english lexicology', 'English Lexicology'),
('syntax', 'Syntax'),
('phonology', 'Phonology'),
('morphology', 'Morphology'),
('semantics and pragmatics', 'Semantics and Pragmatics'),
('sociolinguistics', 'Sociolinguistics'),
('stylistics', 'Stylistics'),
('history of the english language', 'History of the English Language'),
('english phonetics and phonology', 'English Phonetics and Phonology'),
('english morphology', 'English Morphology'),
('english syntax', 'English Syntax'),
('english semantics', 'English Semantics'),
('english pragmatics', 'English Pragmatics'),
('socio-linguistics', 'Socio-Linguistics'),
('english dialects', 'English Dialects'),
('english lexicology', 'English Lexicology'),
('history of the english language', 'History of the English Language'),
('english literature in the 20th century', 'English Literature in the 20th Century'),
('advanced english composition', 'Advanced English Composition'),
('advanced english phonetics and phonology', 'Advanced English Phonetics and Phonology'),
('english morphology', 'English Morphology'),
('english syntax', 'English Syntax'),
('english semantics', 'English Semantics'),
('english pragmatics', 'English Pragmatics'),
('socio-linguistics', 'Socio-Linguistics'),
('english dialectology', 'English Dialectology'),
('english lexicology', 'English Lexicology'),
('history of the english language', 'History of the English Language'),
('english literature in the 19th century', 'English Literature in the 19th Century'),
('introduction to communication skills', 'Introduction to Communication Skills'),
('advanced communication skills', 'Advanced Communication Skills'),
('english for academic purposes', 'English for Academic Purposes'),
('english literature in the 18th century', 'English Literature in the 18th Century'),
('history and structure of the english language', 'History and Structure of the English Language'),
('advanced english composition', 'Advanced English Composition'),
('advanced english phonetics and phonology', 'Advanced English Phonetics and Phonology'),
('advanced english morphology', 'Advanced English Morphology'),
('advanced english syntax', 'Advanced English Syntax'),
('advanced english semantics', 'Advanced English Semantics'),
('advanced english pragmatics', 'Advanced English Pragmatics'),
('advanced socio-linguistics', 'Advanced Socio-Linguistics'),
('advanced english dialectology', 'Advanced English Dialectology'),
('advanced english lexicology', 'Advanced English Lexicology'),
('english dialectology', 'English Dialectology'),
('english phonetics and phonology', 'English Phonetics and Phonology'),
('english morphology', 'English Morphology'),
('english syntax', 'English Syntax'),
('english semantics', 'English Semantics'),
('english pragmatics', 'English Pragmatics'),
('socio-linguistics', 'Socio-Linguistics'),
('english dialectology', 'English Dialectology'),
('english lexicology', 'English Lexicology'),
('english language teaching', 'English Language Teaching'),
('history of the english language', 'History of the English Language'),
('english literature in the 20th century', 'English Literature in the 20th Century'),
('advanced english composition', 'Advanced English Composition'),
('advanced english phonetics and phonology', 'Advanced English Phonetics and Phonology'),
('advanced english morphology', 'Advanced English Morphology'),
('advanced english syntax', 'Advanced English Syntax'),
('advanced english semantics', 'Advanced English Semantics'),
('advanced english pragmatics', 'Advanced English Pragmatics'),
('advanced socio-linguistics', 'Advanced Socio-Linguistics'),
('advanced english dialectology', 'Advanced English Dialectology'),
('advanced english lexicology', 'Advanced English Lexicology'),
('history of the english language', 'History of the English Language'),
('english literature in the 19th century', 'English Literature in the 19th Century'),
('introduction to communication skills', 'Introduction to Communication Skills'),
('advanced communication skills', 'Advanced Communication Skills'),
('english for academic purposes', 'English for Academic Purposes'),
('english literature in the 18th century', 'English Literature in the 18th Century'),
('history and structure of the english language', 'History and Structure of the English Language'),
('advanced english composition', 'Advanced English Composition'),
('advanced english phonetics and phonology', 'Advanced English Phonetics and Phonology'),
('advanced english morphology', 'Advanced English Morphology'),
('advanced english syntax', 'Advanced English Syntax'),
('advanced english semantics', 'Advanced English Semantics'),
('advanced english pragmatics', 'Advanced English Pragmatics'),
('advanced socio-linguistics', 'Advanced Socio-Linguistics'),
('advanced english dialectology', 'Advanced English Dialectology'),
('advanced english lexicology', 'Advanced English Lexicology'),
('english dialectology', 'English Dialectology'),
('english phonetics and phonology', 'English Phonetics and Phonology'),
('english morphology', 'English Morphology'),
('english syntax', 'English Syntax'),
('english semantics', 'English Semantics'),
('english pragmatics', 'English Pragmatics'),
('socio-linguistics', 'Socio-Linguistics'),
('english dialectology', 'English Dialectology'),
('english lexicology', 'English Lexicology'),
('english language teaching', 'English Language Teaching'),
('history of the english language', 'History of the English Language'),
('english literature in the 20th century', 'English Literature in the 20th Century'),
('advanced english composition', 'Advanced English Composition'),
('advanced english phonetics and phonology', 'Advanced English Phonetics and Phonology'),
('advanced english morphology', 'Advanced English Morphology'),
('advanced english syntax', 'Advanced English Syntax'),
('advanced english semantics', 'Advanced English Semantics'),
('advanced english pragmatics', 'Advanced English Pragmatics'),
('advanced socio-linguistics', 'Advanced Socio-Linguistics'),
('advanced english dialectology', 'Advanced English Dialectology'),
('advanced english lexicology', 'Advanced English Lexicology'),
('history of the english language', 'History of the English Language'),
('english literature in the 19th century', 'English Literature in the 19th Century'),
('introduction to communication skills', 'Introduction to Communication Skills'),
('advanced communication skills', 'Advanced Communication Skills'),
('english for academic purposes', 'English for Academic Purposes'),
('english literature in the 18th century', 'English Literature in the 18th Century'),
('history and structure of the english language', 'History and Structure of the English Language'),
('advanced english composition', 'Advanced English Composition'),
('advanced english phonetics and phonology', 'Advanced English Phonetics and Phonology'),
('advanced english morphology', 'Advanced English Morphology'),
('advanced english syntax', 'Advanced English Syntax'),
('advanced english semantics', 'Advanced English Semantics'),
('advanced english pragmatics', 'Advanced English Pragmatics'),
('advanced socio-linguistics', 'Advanced Socio-Linguistics'),
('advanced english dialectology', 'Advanced English Dialectology'),
('advanced english lexicology', 'Advanced English Lexicology'),
('english dialectology', 'English Dialectology'),
('english phonetics and phonology', 'English Phonetics and Phonology'),
('english morphology', 'English Morphology'),
('english syntax', 'English Syntax'),
('english semantics', 'English Semantics'),
('english pragmatics', 'English Pragmatics'),
('socio-linguistics', 'Socio-Linguistics'),
('english dialectology', 'English Dialectology'),
('english lexicology', 'English Lexicology'),
('english language teaching', 'English Language Teaching')]