"""Migrated my database from sqlite to postgres

Revision ID: 2dc4a3a39319
Revises: 
Create Date: 2024-09-12 21:57:12.159004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc4a3a39319'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key constraint first
    op.drop_constraint('scores_course_id_fkey', 'scores', type_='foreignkey')
    op.drop_table('profile_pictures')
    op.drop_table('service_scores')
    op.drop_table('courses')
    op.drop_table('service_subjects')
    op.drop_table('scores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_semester_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('second_semester_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('academic_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cadet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cadet_id'], ['cadets.id'], name='scores_cadet_id_fkey'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='scores_course_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scores_pkey')
    )
    op.create_table('service_subjects',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('service_subjects_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('subject_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('subject_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='service_subjects_service_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_subjects_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('course_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('units', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cadet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cadet_id'], ['cadets.id'], name='courses_cadet_id_fkey'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='courses_department_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='courses_pkey')
    )
    op.create_table('service_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_term_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('second_term_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('service_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cadet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cadet_id'], ['cadets.id'], name='service_scores_cadet_id_fkey'),
    sa.ForeignKeyConstraint(['service_subject_id'], ['service_subjects.id'], name='service_scores_service_subject_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_scores_pkey')
    )
    op.create_table('profile_pictures',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cadet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cadet_id'], ['cadets.id'], name='profile_pictures_cadet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='profile_pictures_pkey')
    )
    # ### end Alembic commands ###
