"""Change date_reported_sick to date type

Revision ID: 7a8bac725b15
Revises: 
Create Date: 2024-05-21 18:16:51.369707+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8bac725b15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battalions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('bn',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)

    with op.batch_alter_table('cadets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('cadet_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('middle_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('religion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('lga',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('date_of_enlistment',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('department_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('bn_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('gender_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('service_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('regular_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('admission_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('board_status',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('admission_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['cadet_no'])
        batch_op.create_foreign_key(None, 'genders', ['gender_id'], ['id'])
        batch_op.create_foreign_key(None, 'regular_courses', ['regular_id'], ['id'])
        batch_op.create_foreign_key(None, 'battalions', ['bn_id'], ['id'])
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'services', ['service_id'], ['id'])

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('course_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('course_title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('units',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('core', 'elective', name='course_status_enum'),
               nullable=False)
        batch_op.alter_column('department_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('cadet_id',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'cadets', ['cadet_id'], ['id'])
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('department_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('faculty_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.create_foreign_key(None, 'faculties', ['faculty_id'], ['id'])

    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('faculty_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)

    with op.batch_alter_table('genders', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('gender_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)

    with op.batch_alter_table('medicals', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('date_reported_sick',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('history',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('examination',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('diagnosis',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('plan',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('prescription',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('excuse_duty',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('excuse_duty_days',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('admission_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('cadet_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.create_foreign_key(None, 'cadets', ['cadet_id'], ['id'])

    with op.batch_alter_table('profile_pictures', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('cadet_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'cadets', ['cadet_id'], ['id'])

    with op.batch_alter_table('regular_courses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('course_no',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('first_semester_score',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('second_semester_score',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('academic_year',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('cadet_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'cadets', ['cadet_id'], ['id'])

    with op.batch_alter_table('service_scores', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('first_term_score',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('second_term_score',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('service_year',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('service_subject_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('cadet_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'service_subjects', ['service_subject_id'], ['id'])
        batch_op.create_foreign_key(None, 'cadets', ['cadet_id'], ['id'])

    with op.batch_alter_table('service_subjects', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('subject_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('subject_title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('major', 'minor', 'tour', 'camp', name='service_subject_status_enum'),
               nullable=False)
        batch_op.alter_column('service_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'services', ['service_id'], ['id'])

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('service_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)

    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.alter_column('staff_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('firstname',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('middlename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('lastname',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('gender_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('appointment',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('date_tos',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('date_of_joining',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('visit_id',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.create_foreign_key(None, 'visits', ['visit_id'], ['id'])
        batch_op.create_foreign_key(None, 'genders', ['gender_id'], ['id'])

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('cadet_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('check_in_time',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('doctor_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'staffs', ['doctor_id'], ['staff_id'])
        batch_op.create_foreign_key(None, 'cadets', ['cadet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('doctor_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('check_in_time',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('cadet_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('visit_id',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('date_of_joining',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('date_tos',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('appointment',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('gender_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=255),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('lastname',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('middlename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('firstname',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('staff_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('service_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('service_subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('service_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('major', 'minor', 'tour', 'camp', name='service_subject_status_enum'),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('subject_title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('subject_code',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('service_scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cadet_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('service_subject_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('service_year',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('second_term_score',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('first_term_score',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cadet_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('academic_year',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('second_semester_score',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('first_semester_score',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('regular_courses', schema=None) as batch_op:
        batch_op.alter_column('course_no',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('profile_pictures', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cadet_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('medicals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cadet_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('admission_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('excuse_duty_days',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('excuse_duty',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('prescription',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('plan',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('diagnosis',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('examination',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('history',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('date_reported_sick',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('genders', schema=None) as batch_op:
        batch_op.alter_column('gender_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.alter_column('faculty_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('faculty_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('department_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cadet_id',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('department_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('core', 'elective', name='course_status_enum'),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('units',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('course_title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('course_code',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('cadets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('admission_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('board_status',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('admission_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('regular_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('service_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('gender_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('bn_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('department_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('date_of_enlistment',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('lga',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('religion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('middle_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('cadet_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('battalions', schema=None) as batch_op:
        batch_op.alter_column('bn',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
