"""Add prescription_status to Medical

Revision ID: cc872143d030
Revises: 2dc4a3a39319
Create Date: 2025-04-19 17:35:00.607067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc872143d030'
down_revision = '2dc4a3a39319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadets', schema=None) as batch_op:
        batch_op.alter_column('date_of_enlistment',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               postgresql_using="date_of_enlistment::date",
               existing_nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               postgresql_using="date_of_birth::date",
               existing_nullable=False)

    with op.batch_alter_table('medicals', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('prescription_status', sa.String(length=50), nullable=False, server_default='pending'))
        
        batch_op.alter_column('excuse_duty',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('excuse_duty_days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cadet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicals', schema=None) as batch_op:
        batch_op.alter_column('cadet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('excuse_duty_days',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('excuse_duty',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('prescription_status')

    with op.batch_alter_table('cadets', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('date_of_enlistment',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
